name: notify-repo-doc.yml
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "Parent-project"
      - run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PARENT_REPO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Test-orga-2ee5d541-2ef3-4a3f-8bac/Parent-project/dispatches \
            -d '{"event_type":"child-docs-updated"}'